### PR TITLE
Drop python 2.6.9 due to issues with urllib3 ssl

### PR DESCRIPTION
**Pull request by meatballhat**
See https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning

### CODE REVIEW

**Comment by alex** [comment]
If you do this, then no one will be able to test anything with python 2.6. Which maybe you want to do, idk? For most of my projects this would mean I'd drop 2.6 support, which maybe isn't unreasonable?

That said, AFAIK 2.6 is still pretty widely used, /cc @dstufft

**Comment by dstufft** [comment]
My latest numbers are from April which showed at least 10% of all of PyPI's downloads were from Python 2.6. There's a good chance some significant amount of the Unknowns are from 2.6 as well.

image

I would prefer it if you didn't remove 2.6 right now, but if you'd like more data (and particularly, more recent data) I can give you access to the raw logs.

**Comment by meatballhat** [comment]
@dstufft do you know of a workaround?  I'm getting `InsecurePlatformWarning` when installing `pip`, which aborts the whole Chef run.  AFAICT I'd have to modify whatever is importing and using `urllib3` in order to get around it.

**Comment by dstufft** [comment]
A warning aborts the chef run? That shouldn't stop anything from running, it's just a warning. Do you have full output available you can show me?

**Comment by meatballhat** [comment]
_[fresh output accumulates]_

**Comment by meatballhat** [comment]
```
INFO: Processing execute[python-build 2.6.9 /opt/python/2.6.9] action run (python::pyenv line 68)
INFO: execute[python-build 2.6.9 /opt/python/2.6.9] ran successfully
INFO: Processing link[/opt/python/2.6.9/bin/python2.6.9] action create (python::pyenv line 73)
INFO: link[/opt/python/2.6.9/bin/python2.6.9] created
INFO: link[/opt/python/2.6.9/bin/python2.6.9] owner changed to 1001
INFO: link[/opt/python/2.6.9/bin/python2.6.9] group changed to 1001
INFO: Processing python_virtualenv[python_2.6.9] action create (python::pyenv line 81)
INFO: Creating virtualenv python_virtualenv[python_2.6.9] at /home/travis/virtualenv/python2.6.9
INFO: Processing execute[virtualenv --distribute --python=/opt/python/2.6.9/bin/python /home/travis/virtualenv/python2.6.9 ] action run (/tmp/chef-stuff/travis-cookbooks/ci_environment/python/providers/virtualenv.rb line 28)
INFO: execute[virtualenv --distribute --python=/opt/python/2.6.9/bin/python /home/travis/virtualenv/python2.6.9 ] ran successfully
INFO: Processing link[/home/travis/virtualenv/python2.6] action create (python::pyenv line 96)
INFO: link[/home/travis/virtualenv/python2.6] created
INFO: link[/home/travis/virtualenv/python2.6] owner changed to 1001
INFO: link[/home/travis/virtualenv/python2.6] group changed to 1001
INFO: Processing execute[install packages 2.6.9] action run (python::pyenv line 115)
INFO: execute[install packages 2.6.9] ran successfully
```

@dstufft @alex thank you for participating in today's episode of That's Funny, Now It Works!

**Comment by dstufft** [comment]
If you were trying this the other day, there was an error that made ``get-pip.py`` fail on Python 2.6 because of release of a dependent project on PyPI that was corrected.

**Comment by meatballhat** [comment]
@dstufft confirm, it was a few days ago! MYSTERY SOLVED

**Pull request closed without merging**
