### PR TITLE
Roll back to jruby-9.0.1.0 on mega

### PR DESCRIPTION
**Pull request by meatballhat**
since building 9.0.3.0 is not going well...

### CODE REVIEW

**Comment by BanzaiMan** [comment]
What sort of issues did you have with 9.0.3.0?

**Comment by meatballhat** [comment]
@BanzaiMan image builds either being OOM killed (in docker) or timing out during `#importing gemset` step (in GCE), the latter being just like in travis-rubies: https://travis-ci.org/travis-ci/travis-rubies/jobs/88348586

**Comment by BanzaiMan** [comment]
I wonder if raising timeout limit may "help".

**Comment by meatballhat** [comment]
@BanzaiMan I'm guessing not much, given the timeout for packer build is configured at 2 hours :neutral_face:

**Comment by BanzaiMan** [comment]
hmmm. I seem to remember an issue like that from somewhere. We should involve Charlie and Tom.

**Comment by meatballhat** [comment]
`"Charlie and Tom".expand!`

**Comment by BanzaiMan** [comment]
@headius and @enebo

**Comment by meatballhat** [comment]
It's happening on jruby-9.0.1.0 now, too, whereas it wasn't ... last week-ish?  I'm ready to accept that this is specific to something in the ubuntu 14.04 environment I'm using, but not sure how to proceed with troubleshooting :confused:

**Comment by meatballhat** [comment]
I think this may be an rvm issue.  Staring at `ps auxwww -u travis | grep ^travis | grep -v 'bash$'` looks like something inside rvm is stuck in a loop.  (note timestamp in top right corner):

rvm-jruby-loop

Taking this thread over to rvm/rvm

**Pull request merged**
